# /migrations/versions/...._add_active_column_to_products.py

"""Add active column to products

Revision ID: 81c7196157a8
Revises: 049f060a4466
Create Date: ...

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '81c7196157a8'
down_revision = '049f060a4466'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:

        batch_op.add_column(
            sa.Column('active', sa.Boolean(),
                      nullable=False,
                      server_default=sa.true())
        )

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('active')

    # ### end Alembic commands ###