"""Add image_file with server_default

Revision ID: 978a5a08dea8
Revises: 1acef1d0c0a3
Create Date: 2025-12-01 14:21:01.974682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '978a5a08dea8'
down_revision = '1acef1d0c0a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_file', sa.String(length=20), server_default='default.jpg', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('image_file')

    # ### end Alembic commands ###
